[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer = false
optimizer_runs = 200
ignored_error_codes=[3628, 5159]

[profile.ref]
src = 'ref'
out = 'out_ref'
libs = ['lib']
optimizer = true
optimizer_runs = 1000000
via_ir=true
cbor_metadata=false
bytecodeHash="none"
ignored_error_codes=[3628, 5159]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config